Nebo24/Nebo24/Nebo24/Models/CommercialFlight.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Nebo24.Models
{
    public class CommercialFlight : Flight
    {

        [Required]
        [Display(Name = "FlightNumber", ShortName = "Number", ResourceType = typeof(Resources.Domain))]
        public string Number { get; set; }
        /*
        public int? CompanyID { get; set; }

        public virtual Company Company { get; set; }
        */
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        [Display(Name = "STDLong", ShortName = "STD", ResourceType = typeof(Resources.Domain))]
        
        public DateTime STD { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        [Display(Name = "ATDLong", ShortName = "ATD", ResourceType = typeof(Resources.Domain))]
        public DateTime? ATD { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        [Display(Name = "STALong", ShortName = "STA", ResourceType = typeof(Resources.Domain))]
        public DateTime STA { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true)]
        [Display(Name = "ATALong", ShortName = "ATA", ResourceType = typeof(Resources.Domain))]
        public DateTime? ATA { get; set; }

    }
}

Nebo24/Nebo24/Nebo24/ViewModels/CommercialFlightViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Nebo24.Models;

namespace Nebo24.ViewModels
{
    public class CommercialFlightViewModel
    {
        public CommercialFlight CommercialFlight { get; set; }

        public double? Delay { get; set; }

        public Airport DepartureAirport { get; set; }

        public Airport DestinationAirport { get; set; }       

    }
}

Nebo24/Nebo24/Nebo24/ViewModels/CommercialFlightsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Nebo24.Models;
using Nebo24.ViewModels;

namespace Nebo24.ViewModels
{
    public class CommercialFlightsViewModel
    {
        public IQueryable<CommercialFlight> CommercialFlights { get; set; }

        public Dictionary<int, double?> Delay { get; set; }

        public FlightsFilterViewModel Filter { get; set; }
    }
}

Nebo24/Nebo24/Nebo24/Controllers/CommercialFlightController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Nebo24.DAL;
using Nebo24.Models;
using Nebo24.Helpers;
using System.Collections.Generic;
using Nebo24.ViewModels;

namespace Nebo24.Controllers
{
    public class CommercialFlightController : BaseController
    {
        private DatabaseContext db = new DatabaseContext();

      
        // GET: CommercialFlight
        public ActionResult Index(DateTime? DepartureTime, DateTime? ArrivalTime, int? DepartureAirportID, int? DestinationAirportID)
        {
            AirportHelper.PopulateAirportsDropDownList(db, ViewBag);

            CommercialFlightsViewModel model = new CommercialFlightsViewModel();
            IQueryable<CommercialFlight> flightList;

            if (DepartureTime.HasValue && ArrivalTime.HasValue) //get flights that should depart in the specified time span
                flightList = db.CommercialFlights.Where(flight => (flight.STD >= DepartureTime) && (flight.STD <= ArrivalTime)).Include(flight => flight.Airplane).Include(flight => flight.DepartureAirport).Include(flight => flight.DestinationAirport);
            else if (DepartureTime.HasValue) //get flights that should depart after the specified date 
                flightList = db.CommercialFlights.Where(flight => (flight.STD >= DepartureTime)).Include(flight => flight.Airplane).Include(flight => flight.DepartureAirport).Include(flight => flight.DestinationAirport);
            else if (ArrivalTime.HasValue)  //get flight that should depart before the specified date
                flightList = db.CommercialFlights.Where(flight => (flight.STD <= ArrivalTime)).Include(flight => flight.Airplane).Include(flight => flight.DepartureAirport).Include(flight => flight.DestinationAirport);
            else //get all flights
                flightList = db.CommercialFlights.Include(flight => flight.Airplane).Include(flight => flight.DepartureAirport).Include(flight => flight.DestinationAirport);

            if (!User.Identity.IsAuthenticated)                                                                    
            {
                DateTime pastBorder = DateTime.Now.AddDays(-7);
                DateTime futureBorder = DateTime.Now.AddDays(7);
                flightList = flightList.Where(flight => (flight.STD >= pastBorder && flight.STA <= futureBorder));                      
            }

            if (DepartureAirportID.HasValue && DestinationAirportID.HasValue)
                flightList = flightList.Where(flight => flight.DepartureAirportID == DepartureAirportID && flight.DestinationAirportID == DestinationAirportID);
            else if (DepartureAirportID.HasValue)
                flightList = flightList.Where(flight => flight.DepartureAirportID == DepartureAirportID);
            else if (DestinationAirportID.HasValue)
                flightList = flightList.Where(flight => flight.DestinationAirportID == DestinationAirportID);

            model.CommercialFlights = flightList.OrderByDescending(t => t.STD).ThenByDescending(t => t.STD);
            model.Delay = CommercialFlightCalculator.getDelays(flightList);

            //get status
            CommercialFlightCalculator.getStatus(flightList);

            model.Filter = new FlightsFilterViewModel();
            
            return View(model);
        }


        // GET: CommercialFlight/Details/5       
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommercialFlight comFlight = db.CommercialFlights.Find(id);
            if (comFlight == null)
            {
                return HttpNotFound();
            }
            CommercialFlightViewModel model = new CommercialFlightViewModel();
            model.CommercialFlight = comFlight;
            model.DepartureAirport = model.CommercialFlight.DepartureAirport;
            model.DestinationAirport = model.CommercialFlight.DestinationAirport;

            if (model.CommercialFlight.ATA.HasValue)
            {
                if (model.CommercialFlight.ATA - model.CommercialFlight.STA >= TimeSpan.FromMinutes(30))
                    model.Delay = (model.CommercialFlight.ATA - model.CommercialFlight.STA).Value.TotalMinutes;
            }
            else if (model.CommercialFlight.ATD.HasValue)
            {
                if (model.CommercialFlight.ATD - model.CommercialFlight.STD >= TimeSpan.FromMinutes(15))
                    model.Delay = (model.CommercialFlight.ATD - model.CommercialFlight.STD).Value.TotalMinutes;
            }
            else
                model.Delay = null;


            CommercialFlightCalculator.getStatus(model.CommercialFlight);

            //CommercialFlight comFlight = db.CommercialFlights.Where(flight => flight.AirplaneID == id).Include(flight => flight.DepartureAirport).Include(flight => flight.DestinationAirport).First();

            return View(model);
        }
        


        //----------------------------------------------------------------------------------
        // GET: CommercialFlight/Create
        [Authorize]
        public ActionResult Create()
        {
            var model = new CommercialFlight();
            
            AirplaneHelper.PopulateAirplaneDropDownList(db, ViewBag);
            AirportHelper.PopulateAirportsDropDownList(db, ViewBag);

            return View("Editor", model);           
        }

        // POST: CommercialFlight/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(CommercialFlight comFlight)
        {
            if (ModelState.IsValid)
            {
                db.CommercialFlights.Add(comFlight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ErrorMessage = ModelState.Values.SelectMany(v => v.Errors);

            AirportHelper.PopulateAirportsDropDownList(db, ViewBag, comFlight.DepartureAirportID);
            AirplaneHelper.PopulateAirplaneDropDownList(db, ViewBag, selectedAirplane: comFlight.AirplaneID);

            return View("Editor", comFlight);
        }
        //--------------------------------------------------------------------------------
        


        //-------------------------------------------------------------------------------       
        // GET: CommercialFlight/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommercialFlight comFlight = db.CommercialFlights.Find(id);
            if (comFlight == null)
            {
                return HttpNotFound();
            }
            
            AirplaneHelper.PopulateAirplaneDropDownList(db, ViewBag, selectedAirplane: comFlight.AirplaneID);
            AirportHelper.PopulateAirportsDropDownList(db, ViewBag, 
                selectedDepartureAirport: comFlight.DepartureAirportID, selectedDestinationAirport: comFlight.DestinationAirportID);

            ViewBag.Editing = true;
            return View("Editor", comFlight);                               
        }


      

        // POST: CommercialFlight/Edit/5
        [Authorize]
        [HttpPost, ActionName("Edit")]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var comFlight = db.CommercialFlights.Find(id);
            if (TryUpdateModel(comFlight))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    ViewBag.Editing = true;
                    View("Editor", comFlight);
                }
            }

            ViewBag.DepartureAirports = new SelectList(db.Airports, "AirportID", "Departure Airport");
            ViewBag.DestinationAirports = new SelectList(db.Airports, "AirportID", "Destination Airport");
            AirplaneHelper.PopulateAirplaneDropDownList(db, ViewBag);
            ViewBag.Editing = true;
            return View("Editor", comFlight);
        }
        //----------------------------------------------------------------------------



        //-------------------------------------------------------------------------------
        // GET: CommercialFlight/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            try
            {
                var comFlight = db.CommercialFlights.Find(id);
                db.CommercialFlights.Remove(comFlight);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }
        }
        //-------------------------------------------------------------------------------            

    }
}

Nebo24/Nebo24/Nebo24/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nebo24.DAL;
using Nebo24.Models;
using Nebo24.Helpers;
using Nebo24.ViewModels;
using System.Data.Entity.Infrastructure;

namespace Nebo24.Controllers
{
    public class CompanyController : BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Company
        public async Task<ActionResult> Index()
        {
            var model = db.Companies.Include(al => al.HeadquartersAdmLoc).Include(gl => gl.HeadquartersGeoLoc).OrderByDescending(fc => fc.Fleet.Count).ThenBy(a => a.Name);
            return View(await model.ToListAsync());
        }


        // GET: Company/Details/5       
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.Include(g => g.HeadquartersAdmLoc).Include(g => g.HeadquartersGeoLoc).SingleOrDefaultAsync(c => c.CompanyID == id);
            if (company == null)
            {
                return HttpNotFound();
            }
            CompanyDetailsViewModel viewModel = new CompanyDetailsViewModel();
            viewModel.Company = company;
            viewModel.Fleet = company.Fleet;
            return View(viewModel);
        }
        

        // GET: Company/Create
        [Authorize]
        public ActionResult Create()
        {
            var model = new Company();
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            return View("Editor", model);
        }

        // POST: Company/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ErrorMessage = ModelState.Values.SelectMany(v => v.Errors);
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: company.HeadquartersAdmLocID);
            return View("Editor", company);
        }

        // GET: Company/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.Include(g => g.HeadquartersAdmLoc).Include(g => g.HeadquartersGeoLoc).SingleOrDefaultAsync(c => c.CompanyID == id);
            if (company == null)
            {
                return HttpNotFound();
            }
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: company.HeadquartersAdmLocID);
            ViewBag.Editing = true;
            return View("Editor", company);
        }

        // POST: Company/Edit/5
        [Authorize]
        [HttpPost, ActionName("Edit")]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = db.Companies.Find(id);
            if (TryUpdateModel(company))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    ViewBag.Editing = true;
                    return View("Editor", company);
                }
            }
            
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            ViewBag.Editing = true;
            return View("Editor", company);
        }

       
        // GET: Company/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            try
            {
                var c = db.Companies.Find(id);
                db.Companies.Remove(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Nebo24/Nebo24/Nebo24/Views/CommercialFlight/Details.cshtml
@model Nebo24.ViewModels.CommercialFlightViewModel
@using System.Globalization;

@{
    ViewBag.Title = Resources.Domain.Flight + ": " + Model.CommercialFlight.Number + " (" + Model.CommercialFlight.Callsign + ")";
}

<div class="header">
    @if (User.Identity.IsAuthenticated)
    {
        <a href="@Url.Action("Edit", "CommercialFlight", new { id = Model.CommercialFlight.FlightID })" class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-edit"></span> @Resources.Label.Edit
        </a>
    }

    <h2>@ViewBag.Title</h2>
</div>

<div class="well col-xs-12 col-sm-6" style="min-height: 250px">
    <dl>
        <dt class="col-xs-6">
            @Resources.Domain.FlightNumber
        </dt>
        <dd class="col-xs-6">
            @Model.CommercialFlight.Number
        </dd>
        <dt class="col-xs-6">
            @Resources.Domain.Callsign
        </dt>
        <dd class="col-xs-6">
            @Model.CommercialFlight.Callsign
        </dd>
        <dt>
            <span class="glyphicon glyphicon-plane"></span>
            @Resources.Domain.Airplane
        </dt>
        <dd class="col-xs-6">
            @Resources.Domain.AirplaneType
        </dd>
        <dd class="col-xs-6">
            <a href="@Url.Action("Details", "AirplaneType", new { id = Model.CommercialFlight.Airplane.Type.AirplaneTypeID })">
                @Model.CommercialFlight.Airplane.Type.Name
            </a>
        </dd>
        <dd class="col-xs-6">
            @Resources.Domain.AirplaneRegistration
        </dd>
        <dd class="col-xs-6">
            @Model.CommercialFlight.Airplane.Registration
        </dd>
        <dt class="col-xs-6">
            @Resources.Domain.FlightStatus
        </dt>
        <dd class="col-xs-6">
            @Html.Partial("~/Views/Shared/_FlightStatusPartial.cshtml", Model.CommercialFlight)
        </dd>
        <dt>
            @Resources.Domain.Company
        </dt>
        <dd class="col-xs-6">
            @Resources.Domain.CompanyName
        </dd>
        <dd class="col-xs-6">
            <a href="@Url.Action("Details", "Company", new { id = Model.CommercialFlight.Airplane.CompanyID })">
                @Model.CommercialFlight.Airplane.Company.Name
            </a>
        </dd>
        <dd class="col-xs-6">
            <span class="glyphicon glyphicon-globe"></span>
            @Resources.Domain.HeadquartersLocation
        </dd>
        <dd class="col-xs-6">
            @Model.CommercialFlight.Airplane.Company.HeadquartersAdmLoc.Location
        </dd>
    </dl>
</div>

<div id="small-map" class="col-xs-12 col-sm-6" style="height: 100%; min-height: 250px"></div>

<div>
    <table class="table table-responsive col-md-6">
        <thead class="">
            <tr>
                <th>

                </th>
                <th>
                    <span class="glyphicon glyphicon-export"></span>
                    @Resources.Domain.Departure
                </th>
                <th>
                    <span class="glyphicon glyphicon-import"></span>
                    @Resources.Domain.Arrival
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>
                    <span class="glyphicon glyphicon-globe"></span>
                    @Resources.Domain.Airports
                </th>
                <th>
                    @Resources.Domain.DepartureAirport
                </th>
                <th>
                    @Resources.Domain.DestinationAirport
                </th>
            </tr>
            <tr>
                <th>
                    @Resources.Domain.AirportName
                </th>
                <td>
                    <a href="@Url.Action("Details", "Airport", new { id = Model.DepartureAirport.AirportID })">
                        @Model.DepartureAirport.Name
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Details", "Airport", new { id = Model.DestinationAirport.AirportID })">
                        @Model.DestinationAirport.Name
                    </a>
                </td>
            </tr>
            <tr>
                <th>
                    @Resources.Domain.AdministrativeLocation
                </th>
                <td>
                    @Model.DepartureAirport.AdmLoc.Location
                </td>
                <td>
                    @Model.DestinationAirport.AdmLoc.Location
                </td>
            </tr>

            <tr>
                <th>
                    <span class="glyphicon glyphicon-time"></span>
                    @Resources.Domain.Times
                </th>
                <th>
                    @Resources.Domain.DepartureTime
                </th>
                <th>
                    @Resources.Domain.ArrivalTime
                </th>
            </tr>
        <tbody>
            <tr>
                <th>
                    @Resources.Domain.Scheduled
                </th>
                <td>
                    @Model.CommercialFlight.STD
                </td>
                <td>
                    @Model.CommercialFlight.STA
                </td>
            </tr>
            <tr>
                <th>
                    @Resources.Domain.Actual
                </th>
                <td>
                    @Model.CommercialFlight.ATD
                </td>
                <td>
                    @Model.CommercialFlight.ATA
                </td>
            </tr>
        </tbody>
    </table>

</div>

@section Scripts
{
    <script>
        function initMap() {
            @if (Model.DepartureAirport == null || Model.DestinationAirport == null)
            {
                 <text>
                    var LatLng1;
                    var LatLng2;
                    LatLng1 = LatLng2 = {lat: 0, lng: 0};
                </text>
            }
            else {
                <text>
                    var LatLng1 = { lat: @Model.DepartureAirport.GeoLoc.Latitude.ToString(CultureInfo.InvariantCulture), lng: @Model.DepartureAirport.GeoLoc.Longitude.ToString(CultureInfo.InvariantCulture) };
                    var LatLng2 = { lat: @Model.DestinationAirport.GeoLoc.Latitude.ToString(CultureInfo.InvariantCulture), lng:  @Model.DestinationAirport.GeoLoc.Longitude.ToString(CultureInfo.InvariantCulture) };
                </text>
            }

            var mapOptions = {
                zoom: 2,
                center: LatLng1,
                disableDefaultUI: true
            }
            var map = new google.maps.Map(document.getElementById("small-map"),
                 mapOptions);
            var marker1 = new google.maps.Marker({
                position: LatLng1,
                map: map,
                label: 'A',
                title: '@Model.DepartureAirport.Name'
            });
            var marker2 = new google.maps.Marker({
                position: LatLng2,
                map: map,
                label: 'B',
                title: '@Model.DestinationAirport.Name'
            })
        }
        $(document).ready(initMap);
    </script>
}

Nebo24/Nebo24/Nebo24/Views/CommercialFlight/Index.cshtml
@using Nebo24.Helpers;
@model Nebo24.ViewModels.CommercialFlightsViewModel

@{
    ViewBag.Title = Resources.Domain.Flights;
}

<div class="header">
    @if (User.Identity.IsAuthenticated)
    {
        <a href="@Url.Action("Create")" class="btn btn-primary pull-right">
            <span class="glyphicon glyphicon-plus"></span> 
            @Resources.Label.CreateFlight
        </a>
    }

    <h2>@ViewBag.Title</h2>
</div>
@{
    ViewBag.FilterByAirport = true;
    @Html.Partial("~/Views/Shared/_FlightsFilterPartial.cshtml", Model.Filter)
}

@if (Model.CommercialFlights.Count() > 0)
{
    @Html.Partial("~/Views/Shared/_FlightsPartial.cshtml", Model)
}
else {
    <div class="alert alert-info">
        <span class="btn-lg glyphicon glyphicon-info-sign"></span> 
        @Resources.Domain.NoFlightsToShow
    </div>
}

@section Scripts {
    @Scripts.Render("~/Scripts/timespan.js");

    <script>
        initializeTimeSpan(
            @if (!User.Identity.IsAuthenticated)
            {
                <text>
                true,
                </text>
            }
            else {
                <text>
                false,
                </text>
            }

        'MM/DD/YYYY hh:mm A');

        $("#SwapAirportsButton").click(function (e) {
            e.preventDefault();

            //Get the values
            var fromVal = $("#DepartureAirportID option:selected").val();
            var fromText = $("#DepartureAirportID option:selected").text();
            var toVal = $("#DestinationAirportID option:selected").val();
            var toText = $("#DestinationAirportID option:selected").text();

            //Set the values
            $("#DepartureAirportID option:selected").val(toVal);
            $("#DepartureAirportID option:selected").text(toText);
            $("#DestinationAirportID option:selected").val(fromVal);
            $("#DestinationAirportID option:selected").text(fromText);
        });
    </script>
}