Nebo24/Nebo24/Nebo24/Controllers/AirportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Nebo24.DAL;
using System.Data.Entity;
using System.Threading.Tasks;
using Nebo24.Models;
using Nebo24.Helpers;
using System.Net;
using Nebo24.ViewModels;
using System.Data.Entity.Core.Objects;
using System.Linq.Expressions;

namespace Nebo24.Controllers
{
    public class AirportController : BaseController
    {

        private DatabaseContext db = new DatabaseContext();

        // GET: Airport
        public async Task<ActionResult> Index()
        {
            var model = db.Airports.Include(al => al.AdmLoc).OrderBy(ap => ap.Name);
            return View(await model.ToListAsync());
        }
        
        // GET: Airport/Details/5
        public ActionResult Details(int? id, DateTime? DepartureTime, DateTime? ArrivalTime)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AirportViewModel model = new AirportViewModel();
            model.Filter = new FlightsFilterViewModel();
            model.Departures = new CommercialFlightsViewModel();
            model.Arrivals = new CommercialFlightsViewModel();
            model.Airport = db.Airports.Find(id);
            model.Departures.CommercialFlights = db.CommercialFlights.Where(d => d.DepartureAirportID == id);
            model.Arrivals.CommercialFlights = db.CommercialFlights.Where(a => a.DestinationAirportID == id);


            //filter departures and arrivals
            if (DepartureTime.HasValue && ArrivalTime.HasValue)  //get flights that should depart from this airport, or arrive in this airport in the specified time span 
            {
                model.Filter.DepartureTime = DepartureTime;
                model.Filter.ArrivalTime = ArrivalTime;
                model.Departures.CommercialFlights = model.Departures.CommercialFlights.Where(flight => (flight.STD >= DepartureTime) && (flight.STD <= ArrivalTime)); //i deleted all includes !!!!!!!!
                model.Arrivals.CommercialFlights = model.Arrivals.CommercialFlights.Where(flight => (flight.STA >= DepartureTime) && (flight.STA <= ArrivalTime)); 
            }
            else if (DepartureTime.HasValue) //get flights that should depart from this airport, or arrive in this airport after the specified date 
            {
                model.Filter.DepartureTime = DepartureTime;
                model.Departures.CommercialFlights = model.Departures.CommercialFlights.Where(flight => (flight.STD >= DepartureTime)); //i deleted all includes !!!!!!!!
                model.Arrivals.CommercialFlights = model.Arrivals.CommercialFlights.Where(flight => (flight.STA >= DepartureTime));
            }
            else if (ArrivalTime.HasValue) //get flights that should depart from this airport, or arrive in this airport before the specified date
            {
                model.Filter.ArrivalTime = ArrivalTime;
                model.Departures.CommercialFlights = model.Departures.CommercialFlights.Where(flight =>  (flight.STD <= ArrivalTime)); //i deleted all includes !!!!!!!!
                model.Arrivals.CommercialFlights = model.Arrivals.CommercialFlights.Where(flight =>  (flight.STA <= ArrivalTime));
            }
            
            //extra filter if user isn't authenticated
            if (!User.Identity.IsAuthenticated)
            {
                DateTime pastBorder = DateTime.Now.AddDays(-7);
                DateTime futureBorder = DateTime.Now.AddDays(7);
                model.Departures.CommercialFlights = model.Departures.CommercialFlights.Where(flight => (flight.STD >= pastBorder && flight.STA <= futureBorder));
                model.Arrivals.CommercialFlights = model.Arrivals.CommercialFlights.Where(flight => (flight.STD >= pastBorder && flight.STA <= futureBorder));
            }


            // get average delays for this airport (filtered flight lists)
            try {
                model.AverageDepartureDelay = model.Departures.CommercialFlights.Where(flight => flight.ATD.HasValue).Average(flight => EntityFunctions.DiffMinutes(flight.STD, flight.ATD).Value);
            }
            catch (InvalidOperationException ex)
            {
                model.AverageDepartureDelay = 0;
            }

            try {
                model.AverageArrivalDelay = model.Arrivals.CommercialFlights.Where(flight => flight.ATA.HasValue).Average(flight => EntityFunctions.DiffMinutes(flight.STA, flight.ATA).Value);
            }
            catch (InvalidOperationException ex) {
                model.AverageArrivalDelay = 0;
            }

            // get delays for each flight
            model.Departures.Delay = CommercialFlightCalculator.getDelays(model.Departures.CommercialFlights);
            model.Arrivals.Delay = CommercialFlightCalculator.getDelays(model.Arrivals.CommercialFlights);

            //get status for flights
            CommercialFlightCalculator.getStatus(model.Departures.CommercialFlights);
            CommercialFlightCalculator.getStatus(model.Arrivals.CommercialFlights);

            return View(model);
        }
        

        // GET: Airport/Create
        [Authorize]
        public ActionResult Create()
        {
            var model = new Airport();
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            return View("Editor", model);
        }

        // POST: Airport/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Airport airport)
        {
            if (ModelState.IsValid)
            {
                db.Airports.Add(airport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ErrorMessage = ModelState.Values.SelectMany(v => v.Errors);
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: airport.AdministrativeLocationID);
            return View("Editor", airport);          
        }

        // GET: Airport/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Airport airport = db.Airports.Find(id);
            if (airport == null)
            {
                return HttpNotFound();
            }
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: airport.AdministrativeLocationID);
            ViewBag.Editing = true;
            return View("Editor", airport);
        }

        // POST: Airport/Edit/5
        [Authorize]
        [HttpPost, ActionName("Edit")]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var airport = db.Airports.Find(id);
            if (TryUpdateModel(airport))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    ViewBag.Editing = true;                    
                    return View("Editor", airport);
                }
            }
       
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            ViewBag.Editing = true;
            return View("Editor", airport);
        }

        
        // GET: Airport/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            try
            {
                var airport = db.Airports.Find(id);
                db.Airports.Remove(airport);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        #region  Old details
        /*
        // GET: Airport/Details/5
        public ActionResult Details(int? id, DateTime? item1, DateTime? item2)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AirportViewModel model = new AirportViewModel();
            Dictionary<int, double> averageDepartureDelays = new Dictionary<int, double>();
            Dictionary<int, double> averageArrivalDelays = new Dictionary<int, double>();
            var airports = db.Airports.Include(al => al.AdmLoc).Include(flights => flights.ArrivingFlights).Include(flights => flights.DepartingFlights);

            foreach (Airport airport in airports)
            {
                model.Departures = new CommercialFlightsViewModel();
                model.Departures.CommercialFlights = db.CommercialFlights.Where(d => d.DepartureAirportID == id);
                try
                {
                    averageArrivalDelays.Add(airport.AirportID, airport.ArrivingFlights.Where(flight => flight.ATA.HasValue).Average(flight => (flight.ATA - flight.STA).Value.TotalMinutes));
                }
                catch (InvalidOperationException ex)  //if there are no arriving flights 
                {
                    averageArrivalDelays.Add(airport.AirportID, 0);
                }
                try
                {
                    model.Arrivals = new CommercialFlightsViewModel();
                    model.Arrivals.CommercialFlights = db.CommercialFlights.Where(a => a.DestinationAirportID == id);
                    averageDepartureDelays.Add(airport.AirportID, airport.DepartingFlights.Where(flight => flight.ATD.HasValue).Average(flight => (flight.ATD - flight.STD).Value.TotalMinutes));
                }

Nebo24/Nebo24/Nebo24/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Nebo24.DAL;
using Nebo24.Models;
using Nebo24.Helpers;
using Nebo24.ViewModels;
using System.Data.Entity.Infrastructure;

namespace Nebo24.Controllers
{
    public class CompanyController : BaseController
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Company
        public async Task<ActionResult> Index()
        {
            var model = db.Companies.Include(al => al.HeadquartersAdmLoc).Include(gl => gl.HeadquartersGeoLoc).OrderByDescending(fc => fc.Fleet.Count).ThenBy(a => a.Name);
            return View(await model.ToListAsync());
        }


        // GET: Company/Details/5       
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.Include(g => g.HeadquartersAdmLoc).Include(g => g.HeadquartersGeoLoc).SingleOrDefaultAsync(c => c.CompanyID == id);
            if (company == null)
            {
                return HttpNotFound();
            }
            CompanyDetailsViewModel viewModel = new CompanyDetailsViewModel();
            viewModel.Company = company;
            viewModel.Fleet = company.Fleet;
            return View(viewModel);
        }
        

        // GET: Company/Create
        [Authorize]
        public ActionResult Create()
        {
            var model = new Company();
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            return View("Editor", model);
        }

        // POST: Company/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ErrorMessage = ModelState.Values.SelectMany(v => v.Errors);
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: company.HeadquartersAdmLocID);
            return View("Editor", company);
        }

        // GET: Company/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = await db.Companies.Include(g => g.HeadquartersAdmLoc).Include(g => g.HeadquartersGeoLoc).SingleOrDefaultAsync(c => c.CompanyID == id);
            if (company == null)
            {
                return HttpNotFound();
            }
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag, selectedAdmLoc: company.HeadquartersAdmLocID);
            ViewBag.Editing = true;
            return View("Editor", company);
        }

        // POST: Company/Edit/5
        [Authorize]
        [HttpPost, ActionName("Edit")]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var company = db.Companies.Find(id);
            if (TryUpdateModel(company))
            {
                try
                {
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    ViewBag.ErrorMessage = e.Message;
                    ViewBag.Editing = true;
                    return View("Editor", company);
                }
            }
            
            AdministrativeLocationHelper.PopulateAdministrativelocationsDropDownList(db, ViewBag);
            ViewBag.Editing = true;
            return View("Editor", company);
        }

       
        // GET: Company/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            try
            {
                var c = db.Companies.Find(id);
                db.Companies.Remove(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Nebo24/Nebo24/Nebo24/Views/Shared/Delete.cshtml
@{
    ViewBag.Title = Resources.Label.Delete;
}

<div class="alert alert-warning large">
    <span class="glyphicon glyphicon-warning-sign"></span> 
    @Resources.Label.CannotBeDeleted
</div>

Nebo24/Nebo24/Nebo24/Views/Shared/_AirplaneTypeInformationPartial.cshtml
<fieldset class="col-md-12" id="AirplaneTypeInformation">
    <legend>
        @Resources.Domain.AirplaneTypeInformation
        <span class="label btn btn-danger pull-right" id="AirplaneTypeCloseButton">
            <span class="glyphicon glyphicon-remove"></span>
        </span>
    </legend>
    <div id="AirplaneTypeInformationContainer"></div>
</fieldset>

Nebo24/Nebo24/Nebo24/Views/Shared/_AirplaneTypesPartial.cshtml
@model IEnumerable<Nebo24.Models.AirplaneType>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Resources.Domain.Name</th>
                <th>@Resources.Domain.ICAONumber</th>
                <th>@Resources.Domain.AverageSpeed <span class="small">km/h</span></th>
                <th>@Resources.Domain.MaximumSpeed <span class="small">km/h</span></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.ICAO
                    </td>
                    <td>
                        @item.AverageSpeed
                    </td>
                    <td>
                        @item.MaximumSpeed
                    </td>
                    <td>
                        <div class="btn-group pull-right">
                            <a href="@Url.Action("Details", new { id = item.AirplaneTypeID })" class="btn btn-info" title="@Resources.Label.Details">
                                <span class="glyphicon glyphicon-info-sign"></span>
                                <span class="hidden-xs hidden-sm">@Resources.Label.Details</span>
                            </a>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="@Url.Action("Edit", new { id = item.AirplaneTypeID })" class="btn btn-success" title="@Resources.Label.Edit">
                                    <span class="glyphicon glyphicon-edit"></span>
                                    <span class="hidden-xs hidden-sm">@Resources.Label.Edit</span>
                                </a>
                                <a href="@Url.Action("Delete", new { id = item.AirplaneTypeID })" class="btn btn-danger" title="@Resources.Label.Delete">
                                    <span class="glyphicon glyphicon-trash"></span>
                                    <span class="hidden-xs hidden-sm">@Resources.Label.Delete </span>
                                </a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Nebo24/Nebo24/Nebo24/Views/Shared/_AirplanesPartial.cshtml
@model IEnumerable<Nebo24.Models.Airplane>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>@Resources.Domain.AirplaneRegistration</th>
                @if (ViewBag.HideAirplaneType == null)
                {
                    <th>@Resources.Domain.AirplaneType</th>
                }
                @if (ViewBag.DisplayOwner != null)
                {
                    <th>@Resources.Domain.CompanyOwner</th>
                }
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Registration
                    </td>
                    @if (ViewBag.HideAirplaneType == null)
                    {
                        <td>
                            @Html.ActionLink(item.Type.Name + " (" + @item.Type.ICAO + ")", "Details", "AirplaneType", new { id = item.AirplaneTypeID }, null)
                        </td>
                    }
                    @if (ViewBag.DisplayOwner != null)
                    {
                        <td>
                            @Html.ActionLink(item.Company.Name, "Details", "Company", new { id = item.CompanyID }, null)
                        </td>
                    }
                    <td>
                        <div class="btn-group pull-right">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a href="@Url.Action("Edit", "Airplane", new { id = item.AirplaneID })" class="btn btn-success" title="@Resources.Label.Edit">
                                    <span class="glyphicon glyphicon-edit"></span> 
                                    <span class="hidden-xs hidden-sm">@Resources.Label.Edit</span>
                                </a>
                                <a href="@Url.Action("Delete", "Airplane", new { id = item.AirplaneID })" class="btn btn-danger" title="@Resources.Label.Delete">
                                    <span class="glyphicon glyphicon-trash"></span> 
                                    <span class="hidden-xs hidden-sm">@Resources.Label.Delete </span>
                                </a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Nebo24/Nebo24/Nebo24/Views/Shared/_BackSaveDiscardButtonsPartial.cshtml
<div class="form-group col-xs-offset-2 col-xs-10">
    <div class="btn-block">
        <a href="@Url.Action("Index")" class="btn btn-info">
            <span class="glyphicon glyphicon-step-backward"></span>
            @Resources.Label.BackToList
        </a>
        <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-floppy-save"></span>
            @Resources.Label.Save
        </button>
        <button type="reset" class="btn btn-danger">
            <span class="glyphicon glyphicon-remove-sign"></span>
            @Resources.Label.Discard
        </button>
    </div>
</div>

Nebo24/Nebo24/Nebo24/Views/Shared/_FlightStatusPartial.cshtml
@model Nebo24.Models.CommercialFlight
@{
    switch ((int)Model.Status)
    {
        case 0:
            <text>
                <span class="label label-primary">
                    @Resources.FlightStatuses.TookOff
                </span>
            </text>
            break;
        case 1:
            <text>
                <span class="label label-success">
                    @Resources.FlightStatuses.Landed
                </span>
            </text>
            break;
        case 2:
            <text>
                <span class="label label-danger">
                    @Resources.FlightStatuses.Canceled
                </span>
            </text>
            break;
        case 3:
            <text>
                <span class="label label-info">
                    @Resources.FlightStatuses.Pending
                </span>
            </text>
            break;
        case 4:
            <text>
                <span class="label label-default">
                    @Resources.FlightStatuses.Crashed
                </span>
            </text>
            break;
        case 5:
            <text>
                <span class="label label-default">
                    @Resources.FlightStatuses.Hijacked
                </span>
            </text>
            break;
        default:
            <text>
                <span class="label label-default">
                    @Resources.FlightStatuses.Unknown
                </span>
            </text>
            break;
    }
}

Nebo24/Nebo24/Nebo24/Views/Shared/_LargeMap.cshtml
<div id="map-container">
    <div id="map-canvas"></div>
    <span id="map-resizer"></span>
</div>

Nebo24/Nebo24/Nebo24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@UICulture.ToString()">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @Resources.App.Name</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap-datetimepicker.min.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="wrapper">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">@Resources.Label.ToggleNavBar</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink(Resources.App.Name, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="@Url.Action("Index", "CommercialFlight")">
                                @Resources.Domain.Flights
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Airport")" >
                                @Resources.Domain.Airports
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Company")">
                                @Resources.Domain.Companies
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                @Resources.Domain.Airplanes
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("Index", "Airplane")">
                                        @Resources.Domain.AllAirplanes
                                    </a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "AirplaneType")">
                                        @Resources.Domain.AirplaneTypes
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <!--
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    -->
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </nav>

        @if (Url.RequestContext.RouteData.Values["controller"].ToString() == "Home" &&
             Url.RequestContext.RouteData.Values["action"].ToString() == "Index")
        {
            @RenderBody();
        }
        else
        {
            <div class="body-content container">
                @RenderBody()
            </div>
        }

        <footer>
            <div class="col-xs-8">
                <p>
                    &copy; @DateTime.Now.Year - @Resources.App.Name (<a href="@Resources.App.URL">@Resources.App.URL</a>)
                    <div>
                        <span class="h3">
                            @Resources.App.Company,
                        </span>
                        <span class="h3 text-capitalize">
                            <a href="https://www.fer.unizg.hr">
                                FER
                            </a>
                        </span>
                    </div>
            </div>
            <div class="col-xs-4 sponsor pull-right">
                <div>
                    Windows Cloud Hosting
                </div>
                <a href="https://www.terrakom.hr">
                    <img src="https://www.terrakom.hr/static/images/terrakom-logo-small.png?adff6ba9506ca814" class="img-responsive" alt="Terrakom" />
                </a>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/moment-with-locales.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
    <script src="https://maps.googleapis.com/maps/api/js?language=@UICulture"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Nebo24/Nebo24/Nebo24/Views/Shared/_ValidationSummaryPartial.cshtml
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })